pipeline:
  name: pipeline-ai-test
  identifier: pipelineaitest
  projectIdentifier: RnDai
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: shubhampardeshi26
        repoName: harness-ai
        build: <+input>
  stages:
    - stage:
        name: Checkout Code
        identifier: Checkout_Code
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: shubhampardeshi26
                    repoName: harness-ai
                    cloneDirectory: <+input>
                    build:
                      type: branch
                      spec:
                        branch: <+input>
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Python
                    command: pip install -r requirements.txt
                  description: Install Requirements.txt
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Python
                    command: pytest > final_test_report.logs
                  description: Test cases
        delegateSelectors:
          - docker-delegate-local
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: MarkAsFailure
    - stage:
        name: approval
        identifier: approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: CustomApproval
                  name: TL approval
                  identifier: TL_approval
                  timeout: 1d
                  spec:
                    shell: Bash
                    retryInterval: 10s
                    scriptTimeout: 10m
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash

                          read -p "Are you TL? (yes/no): " is_tl

                          if [ "$is_tl" == "yes" ]; then
                              read -p "Do you want to deploy? (yes/no): " deploy
                              if [ "$deploy" == "yes" ]; then
                                  echo "true"
                                  exit 0
                              else
                                  echo "false"
                                  exit 1
                              fi
                          else
                              echo "false"
                              exit 1
                          fi
                    environmentVariables: []
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions:
                          - key: deploy
                            operator: equals
                            value: "yes"
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions: []
                    onDelegate: true
                    outputVariables:
                      - name: is_tl
                        type: String
                        value: "no"
                    delegateSelectors:
                      - docker-delegate-local
        tags: {}
        delegateSelectors:
          - docker-delegate-local
        when:
          pipelineStatus: Success
